name: 🚀 Make Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Release
        run: |
          mkdir release
          mv addons/MonoCustomResourceRegistry release
          pushd release
          zip -r ../Release.zip *
          popd
      
      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: Release
          path: release

      - name: Tagged Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Release.zip